---

rubies_dir: ~/.rubies

# NOTE: The *first* listed Ruby version will be the *default*.
# Note that SHA256 signatures are for BZ2 files; get them from the ruby-lang.org release announcements.
ruby_versions:
  - engine: ruby
    version: 2.5.1
    sha256: 0f5d20f012baca865381a055e73f22db814615fee3c68083182cb78a4b3b30cb
  - engine: ruby
    version: 2.4.4
    sha256: 45a8de577471b90dc4838c5ef26aeb253a56002896189055a44dc680644243f1
  - engine: ruby
    version: 2.3.7
    sha256: 18b12fafaf37d5f6c7139c1b445355aec76baa625a40300598a6c8597fc04d8e
  - engine: ruby
    version: 2.2.10
    sha256: a54204d2728283c9eff0cf81d654f245fa5b3447d0824f1a6bc3b2c5c827381e

gems_for_all_rubies:
  - bundler
  - railties
  - rubocop
  - pry
  - pry-doc # All these Pry tools can be pulled in via `pry-full`, but that fails installing `pry-git` and `pry-debugger` in Ruby 2.5.0.
  - pry-docmore
  - pry-stack_explorer
  - pry-rescue
  - pry-theme
  - pry-pretty-numeric
  - pry-highlight
  - pry-editline
  - pry-developer_tools
  - bond # Better tab completion for Pry
  - awesome_print
  - hirb
  - wirble
  - solargraph
  - ruby-debug-ide
  - debase

gems_for_latest_ruby:
  - kramdown
  - rsense
  - ruby-beautify
  - middleman
  - middleman-presentation
